/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#263143",
        "error-container": "#93000a",
        "surface": "#0b1326",
        "on-tertiary": "#003547",
        "inverse-surface": "#dae2fd",
        "on-primary": "#003543",
        "tertiary-fixed-dim": "#7bd1fa",
        "outline-variant": "#3c494e",
        "on-tertiary-fixed": "#001e2b",
        "surface-variant": "#2d3449",
        "secondary": "#bcc7de",
        "surface-tint": "#4cd6ff",
        "primary": "#a4e6ff",
        "tertiary": "#b0e3ff",
        "tertiary-fixed": "#c0e8ff",
        "primary-fixed": "#b7eaff",
        "on-tertiary-fixed-variant": "#004d66",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary-container": "#00566a",
        "surface-container-high": "#222a3d",
        "outline": "#859399",
        "error": "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "surface-container-lowest": "#060e20",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "secondary-fixed": "#d8e3fb",
        "surface-bright": "#31394d",
        "primary-container": "#00d1ff",
        "on-secondary-container": "#aeb9d0",
        "inverse-primary": "#00677f",
        "on-error": "#690005",
        "on-primary-fixed": "#001f28",
        "on-secondary-fixed": "#111c2d",
        "tertiary-container": "#75cbf4",
        "primary-fixed-dim": "#4cd6ff",
        "surface-dim": "#0b1326",
        "on-tertiary-container": "#005570",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bbc9cf",
        "on-primary-fixed-variant": "#004e60",
        "surface-container": "#171f33",
        "background": "#0b1326",
        "on-background": "#dae2fd",
        "secondary-container": "#3e495d"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
